### ISSUE TITLE
little advice 0.0

### ISSUE THREAD

**Issue by shenw8023** [serend1p1ty/core-pytorch-utils#1]
https://github.com/serend1p1ty/core-pytorch-utils/blob/80016b90c69e1204b6dd7531a1ef0de3fe7f73d9/cpu/hooks/logger_hook.py#L73

inner_iter starts from 0, I this this might be better: 
`process_string = f"Epoch: [{self.trainer.epoch}][{self.trainer.inner_iter + 1}/{self.trainer.epoch_len}]"`

**Comment by serend1p1ty** [comment]
It is mainly considered that counting from 0 is more in line with the thinking of programmers.

PS: `self.trainer.epoch` is a 0-based counter also. So you may want
`process_string = f"Epoch: [{self.trainer.epoch + 1}][{self.trainer.inner_iter + 1}/{self.trainer.epoch_len}]"`
