### ISSUE TITLE
when save checkpoints,  oom occured

### ISSUE THREAD

**Issue by liwenju0** [serend1p1ty/core-pytorch-utils#7]
i have debug this problem for a long time, now i think  the core reason is  that saving too many state ,not only weights of model, but also optimizer state_dict.
if want to avoid oom during training,  a solution is to decrease the batch size, but will cause a waster of gpu memory
is it better to save optimizer state stand alone?

**Comment by serend1p1ty** [comment]
You can create `ModelWeightsOnlyCheckpointHook` for your case.

**Comment by serend1p1ty** [comment]
But I think saving the optimizer state is a better choice, after all, the role of checkpoint is not only to evaluate model performance but also to support resuming training.
